spring:
  application:
    name: meli-validation-api
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/melidatabase
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 2
      pool-name: KrakenPool

server:
  port: 8080
  servlet:
    context-path: /meli/validation

logging:
  level:
    com.familia: DEBUG
    
meli:
  url-api-ip: http://api.ipapi.com/
  access-key-ip: de472c60002d81a2325f181bd3a82c8d
  url-api-info-country: http://api.countrylayer.com/v2/name/
  access-key-info-country: 015ee4b6aff06f099b44a7866770904f
  url-api-info-currency-country: http://data.fixer.io/api/latest
  access-key-info-currency-country: e1821fc9ab21b037e49a28f7a8968f85