spring:
  application:
    name: meli-validation-api
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/melidatabase
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 2
      pool-name: MeliPool

server:
  port: 8080
  servlet:
    context-path: /meli/validation

logging:
  level:
    com.mercadolibre: DEBUG
    
meli:
  url-api-ip: http://api.ipapi.com/
  access-key-ip: 2c8bcab451a4c849487a6f56ce24adb5
  url-api-info-country: http://api.countrylayer.com/v2/alpha/
  access-key-info-country: 849313f8657a77ee3262097c39aac554
  url-api-info-currency-country: http://data.fixer.io/api/latest
  access-key-info-currency-country: d88d94262550ab1739347df3777a02b1